### ISSUE TITLE
HTTP 500 "Failed to update source" when creating or editing Sources in Local App Mode

### ISSUE THREAD

**Issue by EngineTech** [hyperdxio/hyperdx#2600]
Starting from **@hyperdx/app@v2.22.0**, it is no longer possible to create a new Source or edit an existing one from **Team Settings → Data → Sources** when running HyperDX with:

```text
IS_LOCAL_APP_MODE="DANGEROUSLY_is_local_app_mode💀"
```

The UI returns:

```
HTTP 500
Failed to update source
```

The problem only occurs when Local App Mode is enabled (used together with an external authentication solution). The same deployment works correctly on **v2.21.0**.

## Steps to Reproduce

1. Deploy HyperDX **v2.22.0 or newer**.
2. Set:

   ```text
   IS_LOCAL_APP_MODE="DANGEROUSLY_is_local_app_mode💀"
   ```
4. Open **Team Settings → Data → Sources**.
5. Try to:

   * create a new Source, or
   * edit an existing Source.
6. Save the changes.

## Expected Behavior

The Source should be created or updated successfully.

## Actual Behavior

The request fails with HTTP 500 and the UI displays:

```
Failed to update source
```

## Server Logs

```text
TypeError: teamId.toJSON is not a function
    at /app/packages/api/build/routers/api/sources.js:49:26
```

The API returns HTTP 500 for requests such as:

```text
PUT /sources/<source-id>
```

Full logs are attached below.

<details>
<summary>Full server logs</summary>

```text
hyperdx-noauth-1  | [API] TypeError: teamId.toJSON is not a function
hyperdx-noauth-1  | [API]     at /app/packages/api/build/routers/api/sources.js:49:26
hyperdx-noauth-1  | [API]     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
hyperdx-noauth-1  | [API]     at next (/app/node_modules/express/lib/router/route.js:149:13)
hyperdx-noauth-1  | [API]     at /app/node_modules/zod-express-middleware/lib/index.js:147:16
hyperdx-noauth-1  | [API]     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
hyperdx-noauth-1  | [API]     at next (/app/node_modules/express/lib/router/route.js:149:13)
hyperdx-noauth-1  | [API]     at Route.dispatch (/app/node_modules/express/lib/router/route.js:119:3)
hyperdx-noauth-1  | [API]     at patched (/app/node_modules/@opentelemetry/instrumentation-express/build/src/instrumentation.js:210:37)
hyperdx-noauth-1  | [API]     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
hyperdx-noauth-1  | [API]     at /app/node_modules/express/lib/router/index.js:284:15
hyperdx-noauth-1  | [API] {"level":40,"time":1783434714216,"pid":14,"hostname":"8fb81a392b21","trace_id":"94a85c709f023c63fcbd4816c1cc2dab","span_id":"b92f4903c7ae7efa","trace_flags":"01","msg":"Skipping authentication in local app mode"}
hyperdx-noauth-1  | [API] {"level":50,"time":1783434714231,"pid":14,"hostname":"8fb81a392b21","req":{"id":37,"method":"PUT","url":"/sources/697b68e0fa09ac06447479d1","query":{},"params":{},"headers":{"x-forwarded-for":"172.18.0.9","x-forwarded-proto":"http","x-forwarded-port":"8080","x-forwarded-host":"hyperdx-noauth:8080","priority":"u=0","sec-gpc":"1","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","cookie":"__rum_sid=%7B%22id%22%3A%22576647329796a6fa5b4b5ae57a2c172b%22%2C%22startTime%22%3A1783433661988%7D; _oauth2_proxy=BhOu...","origin":"https://10.80.52.122","traceparent":"00-94a85c709f023c63fcbd4816c1cc2dab-f20eecd0346de699-01","content-type":"application/json","referer":"https://10.80.52.122/team?source=6a4cb22df11cb05acca98611&tab=data","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7","accept":"*/*","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:150.0) Gecko/20100101 Firefox/150.0","content-length":"410","connection":"close","host":"127.0.0.1:8000"},"remoteAddress":"::ffff:127.0.0.1","remotePort":41986},"userId":"_local_user_","userEmail":"local-user@hyperdx.io","trace_id":"94a85c709f023c63fcbd4816c1cc2dab","span_id":"b92f4903c7ae7efa","trace_flags":"01","res":{"statusCode":500,"headers":{"access-control-allow-origin":"http://10.80.52.122","vary":"Origin, Accept-Encoding","access-control-allow-credentials":"true","content-type":"application/json; charset=utf-8","content-length":"37","etag":"W/\"25-aJ2RnUVcDxeUcfymWAtzMxkwbO4\"","timing-allow-origin":"http://10.80.52.122"}},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at onResFinished (/app/node_modules/pino-http/logger.js:115:39)\n    at ServerResponse.onResponseComplete (/app/node_modules/pino-http/logger.js:178:14)\n    at /app/node_modules/@hyperdx/node-opentelemetry/build/src/AbstractAsyncHooksContextManager.js:29:55\n    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)\n    at MutableAsyncLocalStorageContextManager.with (/app/node_modules/@hyperdx/node-opentelemetry/build/src/MutableAsyncLocalStorageContextManager.js:22:40)\n    at ServerResponse.contextWrapper (/app/node_modules/@hyperdx/node-opentelemetry/build/src/AbstractAsyncHooksContextManager.js:29:32)\n    at ServerResponse.emit (node:events:531:35)\n    at onFinish (node:_http_outgoing:1084:10)\n    at callback (node:internal/streams/writable:766:21)\n    at afterWrite (node:internal/streams/writable:710:5)"},"responseTime":16,"msg":"HTTP PUT /sources/697b68e0fa09ac06447479d1"}
```

</details>

## Workaround

Downgrade to **@hyperdx/app@v2.21.0**, where Source management works correctly in Local App Mode.

**Comment by brandon-pereira** [comment]
Hey there @EngineTech  - good find. We will prioritize this fix. If you have capacity to open a PR I am happy to review it :)

**Comment by EngineTech** [comment]
@brandon-pereira thanks for prioritizing and quick fix! When I wrote issue I only had time to look at the diff between versions 2.21.0 and 2.22.0.
